In [1]:
import torch

In [2]:
import torch.nn as nn

In [3]:
import numpy as np

In [9]:
input_data = torch.tensor([1.0, 2.0])

In [10]:
layer1 = nn.Linear(2, 3)

In [11]:
layer1(input_data)

tensor([-1.3630,  0.1410,  0.7285], grad_fn=<AddBackward0>)

In [22]:
layer1.weight

Parameter containing:
tensor([[-0.4123, -0.5623],
        [ 0.5934, -0.2864],
        [ 0.6924, -0.2508]], requires_grad=True)

In [14]:
layer1.bias

Parameter containing:
tensor([0.1739, 0.1205, 0.5376], requires_grad=True)

In [26]:
network = nn.Sequential(nn.Linear(2, 3), nn.ReLU(), nn.Linear(3, 10), nn.ReLU())

In [27]:
network(input_data)

tensor([0.4413, 0.4363, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.1824,
        0.1257], grad_fn=<ReluBackward0>)

In [31]:
network[:2]

Sequential(
  (0): Linear(in_features=2, out_features=3, bias=True)
  (1): ReLU()
)